FROM redis:latest

# Copy custom Redis configuration
COPY redis.conf /usr/local/etc/redis/redis.conf

# Expose the Redis port
EXPOSE 6379

# Run Redis with the custom configuration file
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
